const MOCK_HOST_ADDRESS = '127.0.0.1';
const MOCK_HOST = `http://${MOCK_HOST_ADDRESS}`;

const MOCK_SRL_BASE_URL_PORT = 4000;
const MOCK_SRL_BASE_URL = `${MOCK_HOST}:${MOCK_SRL_BASE_URL_PORT}`;

const MOCK_SRL_API_BASE_URL_PORT = 4001;
const MOCK_SRL_API_BASE_URL = `${MOCK_HOST}:${MOCK_SRL_API_BASE_URL_PORT}`;

const MOCK_RACETIME_BASE_URL_PORT = 4002;
const MOCK_RACETIME_BASE_URL = `${MOCK_HOST}:${MOCK_RACETIME_BASE_URL_PORT}`;

export {
  MOCK_HOST,
  MOCK_HOST_ADDRESS,
  MOCK_SRL_BASE_URL,
  MOCK_SRL_BASE_URL_PORT,
  MOCK_SRL_API_BASE_URL,
  MOCK_SRL_API_BASE_URL_PORT,
  MOCK_RACETIME_BASE_URL,
  MOCK_RACETIME_BASE_URL_PORT,
};
